function main():
	for x = ('a','b','c'):
		pass
	break
	return 'ok'
+++error 4 YERROR_UNEXPECTED_BREAK_CONTINUE_FINALLY_RESTART
