function f(a,b):
	pass
function main():
	f(1,2,a=1)
	return 'ok'
+++exception YEXCEPTION_PARAMASSIGNEDTWICE 4
