function main():
	function close(): raise $exception()
	with a1=close:
		pass
	return 'ok'
+++exception USER 2 3
